export const environment = {
  production: true,
  movies:
  {
      API_BASE_URL: 'https://api.themoviedb.org/3/search/movie?',
      API_KEY: 'af708b4d3ed724d2d43f01c3eb56291d',
      IMAGE_URL: 'https://image.tmdb.org/t/p/w500',
      NO_IMAGE: 'assets/images/no-image.jpg',
      CATEGORY_STRING: {
        ADULT: 'Adults Only',
        ADULT_ONLY: 'No Adult Only'    
      }
  },
  languages: {
    list: ['af', 'ach', 'ak', 'am', 'ar', 'az', 'be', 'bg',
      'bh', 'bn', 'br', 'bs', 'ca', 
      'co',  'cs', 'cy', 'da', 'de', 'ee', 'el', 'en', 'eo', 'es', 
      'es-419', 'et', 'eu', 'fa', 'fi', 
      'fo','fr', 'fy', 'ga', 'gd', 'gl', 'gn', 'gu', 'ha', 
      'hi', 'hr', 'ht', 'hu', 'hy', 'ia', 
      'id','ig', 'is', 'ja', 'ka', 'kg',
      'kk','km', 'kn', 'ko', 'ku', 'ky', 'la', 
      'lg','ln', 'ml', 'mn', 'mo', 'mr', 'ms', 'mt',
      'ne','nl', 'nn', 'no', 'ny',  'oc', 'om', 
      'or','pa', 'pcm', 'pl', 'ps', 'pt-BR', 
      'pt-PT', 'qu', 'rm', 'rn', 'ro', 'ru', 'rw', 'sd', 'sh', 
      'si, sk', 'sl', 'sn', 'so', 'sq', 'sr', 
      'sr-ME', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 
      'th', 'ti', 'tk', 'tl', 'tn', 'to', 'tr', 'tt', 
      'tum', 'tw, ug', 'uk', 'ur', 'uz', 'vi', 'wo', 
      'xh', 'xx-bork', 'xx-elmer', 'xx-hacker', 
      'xx-klingon', 'xx-pirate', 'yi', 'yo', 
      'zh-CN', 'zh-TW', 'zu'],
     name: {
      af: 'Afrikaans',
      ak: 'Akan',
      am: 'Amharic',
      ar: 'Arabic',
      az: 'Azerbaijani',
      be: 'Belarusian',
      bg: 'Bulgarian',
      bh: 'Bihari',
      bn: 'Bengali',
      br: 'Breton',
      bs: 'Bosnian',
      ca: 'Catalan',
      co: 'Corsican',
      cs: 'Czech',
      cy: 'Welsh',
      da: 'Danish',
      de: 'German',
      ee: 'Ewe',
      el: 'Greek',
      en: 'English',
      eo: 'Esperanto',
      es: 'Spanish', 
      et: 'Estonian',
      eu: 'Basque',
      fa: 'Persian',
      fi: 'Finnish',
      fo: 'Faroese',
      fr: 'French',
      fy: 'Western Frisian',
      ga: 'Irish',
      gd: 'Scottish',
      gl: 'Galician',
      gn: 'Guarani',
      gu: 'Gujarati',
      ha: 'Hausa',
      hi: 'Hindi',
      hr: 'Croatian',
      ht: 'Haitian Creole',
      hu: 'Hungarian',
      hy: 'Armenian',
      ia: 'Interlingua',
      id: 'Indonesian',
      ig: 'Igbo',
      is: 'Icelandic',
      ja: 'Japanese',
      ka: 'Georgian',
      kg: 'Kongo',
      kk: 'Kazakh',
      km: 'Khmer',
      kn: 'Kannada',
      ko: 'Korean',
      ku: 'Kurdish',
      ky: 'Kyrgyz',
      la: 'Latin',
      lg: 'Luganda',
      ln: 'Lingala',
      ml: 'Malayalam',
      mn: 'Mongolian',
      mo: 'Moldavian',
      mr: 'Marathi',
      ms: 'Malay',
      mt: 'Maltese',
      ne: 'Nepali',
      nl: 'Dutch',
      nn: 'Norwegian nynorsk',
      no: 'Norwegian',
      ny: 'Chichewa',
      oc: 'Occitan',
      om: 'Oromo',
      or: 'Oriya',
      pa: 'Punjabi',
      pl: 'Polish',
      ps: 'Pushto',
      ta: 'Tamil',
      te: 'Telugu'
    }
  }
};
